export const TRADUCCIONES = {
  es: {
    // Generales
    cargando: 'Cargando...',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    volver: '← Volver',
    confirmar: 'Confirmar',
    eliminar: 'Eliminar',
    salir: 'Salir',
    siguiente: 'Siguiente',
    anterior: 'Anterior',

    // Tutorial
    tutorial_paso1_titulo: 'Bienvenido a MediCaduca',
    tutorial_paso1_texto: 'La app para controlar la caducidad de tus medicamentos. Fácil, rápido y gratis.',
    tutorial_paso2_titulo: 'Añade tus medicamentos',
    tutorial_paso2_texto: 'Escanea el código de barras o escribe a mano el nombre y la fecha de caducidad.',
    tutorial_paso3_titulo: 'Recibe alertas',
    tutorial_paso3_texto: 'Te avisamos por colores: verde, naranja o rojo según el estado de cada medicamento.',
    tutorial_paso4_titulo: 'Comparte con tu familia',
    tutorial_paso4_texto: 'Hazte Premium y controla el botiquín de toda la familia desde un solo sitio.',
    tutorial_empezar: 'Empezar',

    // Rol
    rol_titulo: 'Elige tu perfil',
    rol_subtitulo: 'Te recomendaremos las funciones que más te interesan',
    rol_hogar: 'Hogar',
    rol_hogar_desc: 'Controla el botiquín de tu familia',
    rol_hospital: 'Hospital',
    rol_hospital_desc: 'Stock y caducidades por planta o unidad',
    rol_farmacia: 'Farmacia',
    rol_farmacia_desc: 'Lotes, referencias y caducidades',
    rol_medico: 'Médico',
    rol_medico_desc: 'Medicación por paciente o expediente',

    // Registro/Login
    registro_titulo: 'Crear cuenta',
    login_titulo: 'Iniciar sesión',
    nombre: 'Nombre',
    email: 'Email',
    password: 'Contraseña',
    crear_cuenta: 'Crear cuenta',
    iniciar_sesion: 'Iniciar sesión',
    ya_tengo_cuenta: '¿Ya tienes cuenta? Inicia sesión',
    no_tengo_cuenta: '¿No tienes cuenta? Regístrate',
    olvide_password: '¿Olvidaste la contraseña?',
    recuperar_titulo: 'Recuperar contraseña',
    recuperar_texto: 'Te enviaremos un enlace para crear una contraseña nueva',
    recuperar_boton: 'Enviar enlace',
    recuperar_enviado: 'Te hemos enviado un email. Revisa tu bandeja de entrada.',

    // App principal
    total: 'Total',
    pronto: 'Pronto',
    caducados: 'Caducados',
    tab_medicamentos: '💊 Medicamentos',
    tab_anadir: '➕ Añadir',
    tab_alertas: '🔔 Alertas',
    sin_medicamentos: 'Sin medicamentos. ¡Añade el primero!',
    sin_alertas: '✅ Sin alertas pendientes',
    compartir_mi_botiquin: '👥 Compartir mi botiquín',
    compartir: '👥 Compartir',
    sin_anuncios: '👑 Sin anuncios — 1,99 €/mes',
    modo_lectura: '👁️ Estás viendo el botiquín de otro usuario en modo lectura. Solo el dueño puede modificarlo.',
    exportar_pdf: '📄 Exportar PDF',
    exportar_pdf_premium: '📄 Exportar PDF (Premium)',
    exportar_generando: '📄 Generando...',
    mi_botiquin: 'Mi botiquín',
    botiquin_de: 'Botiquín de',

    // Estados de medicamentos
    estado_ok: 'En vigor',
    estado_pronto: 'Caduca pronto',
    estado_urgente: 'Muy pronto',
    estado_caducado: 'Caducado',
    dias_caducado: 'Caducado hace {dias} días',
    dias_caduca_hoy: 'Caduca hoy',
    dias_caduca_en: 'Caduca en {dias} días',
    sin_fecha: 'Sin fecha',

    // Categorías
    cat_analgesico: 'Analgésico',
    cat_antibiotico: 'Antibiótico',
    cat_antihistaminico: 'Antihistamínico',
    cat_digestivo: 'Digestivo',
    cat_vitamina: 'Vitamina',
    cat_otro: 'Otro',

    // Añadir
    nuevo_medicamento: '💊 Nuevo medicamento',
    modo_escribir: '⌨️ Escribir',
    modo_escanear: '📷 Escanear código',
    categoria: 'Categoría',
    fecha_caducidad: 'Fecha de caducidad',
    fecha_caducidad_ayuda: '(está en la caja)',
    cantidad: 'Cantidad (opcional)',
    mes: 'Mes',
    anio: 'Año',
    boton_anadir_medicamento: '➕ Añadir medicamento',
    escanea_codigo: 'Escanea el código de barras',
    escanea_ayuda: 'Pulsa abajo y haz una foto del código',
    activar_camara: '📷 Activar cámara',
    buscando_cima: 'Buscando en CIMA...',
    medicamento_detectado: '✅ Medicamento detectado',
    mira_caducidad_caja: '(mírala en la caja)',
    guardar_medicamento: '✓ Guardar',

    // Meses
    meses: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],

    // Perfil
    mi_perfil: 'Mi perfil',
    datos_personales: 'Datos personales',
    recibir_avisos: 'Recibir avisos por email cuando un medicamento caduque pronto',
    guardar_cambios: 'Guardar cambios',
    perfil_actualizado: 'Perfil actualizado correctamente',
    cambiar_password: 'Cambiar contraseña',
    nueva_password: 'Nueva contraseña (mín. 6 caracteres)',
    password_cambiada: 'Contraseña cambiada correctamente',
    zona_peligrosa: 'Zona peligrosa',
    eliminar_cuenta_aviso: 'Eliminar tu cuenta borrará todos tus medicamentos y datos para siempre. No se puede deshacer.',
    eliminar_mi_cuenta: 'Eliminar mi cuenta',
    escribe_eliminar: 'Escribe ELIMINAR para confirmar:',
    confirmar_eliminacion: 'Confirmar eliminación',
    suscripcion_activa: '👑 Suscripción Premium activa',
    suscripcion_descripcion: 'Gestiona tu suscripción, cambia el método de pago, ve tus facturas o cancela cuando quieras.',
    gestionar_suscripcion: 'Gestionar suscripción',
    abriendo: 'Abriendo...',
    idioma: 'Idioma',

    // Compartir
    compartir_titulo: 'Compartir botiquín',
    compartir_premium_aviso: 'Compartir el botiquín es una función Premium. Hazte Premium para invitar a familiares o cuidadores.',
    invitar_familiar: 'Invitar familiar',
    invitar_email: 'Email del familiar o cuidador',
    invitar_boton: 'Enviar invitación',
    invitacion_enviada: 'Invitación enviada',
    miembros_titulo: 'Miembros del botiquín',
    invitaciones_pendientes: 'Invitaciones pendientes',
    aceptar: 'Aceptar',
    rechazar: 'Rechazar',
    sin_miembros: 'Aún no has invitado a nadie',
    sin_invitaciones: 'No tienes invitaciones pendientes',
    limite_invitados: 'Has alcanzado el máximo de 4 invitados',

    // Errores comunes
    error_email_password: 'Email o contraseña incorrectos',
    error_email_existe: 'Este email ya está registrado',
    error_generico: 'Ha ocurrido un error. Inténtalo de nuevo.',
    error_password_corta: 'La contraseña debe tener al menos 6 caracteres',
    error_completa_campos: 'Completa todos los campos',
    medicamento_anadido: '{nombre} añadido',
    medicamento_eliminado: 'Medicamento eliminado',
    rellena_nombre_fecha: 'Escribe el nombre y selecciona la fecha',
    solo_dueno_anadir: 'Solo el dueño puede añadir',
    solo_dueno_eliminar: 'Solo el dueño puede eliminar',
    pdf_descargado: 'PDF descargado',
    pdf_premium_aviso: 'Exportar PDF es una función Premium',
  },

  eu: {
    // Generales
    cargando: 'Kargatzen...',
    guardar: 'Gorde',
    cancelar: 'Utzi',
    volver: '← Itzuli',
    confirmar: 'Berretsi',
    eliminar: 'Ezabatu',
    salir: 'Irten',
    siguiente: 'Hurrengoa',
    anterior: 'Aurrekoa',

    // Tutorial
    tutorial_paso1_titulo: 'Ongi etorri MediCaducara',
    tutorial_paso1_texto: 'Zure botiken iraungitze-data kontrolatzeko aplikazioa. Erraza, azkarra eta doan.',
    tutorial_paso2_titulo: 'Gehitu zure botikak',
    tutorial_paso2_texto: 'Eskaneatu kode-barra edo idatzi eskuz izena eta iraungitze-data.',
    tutorial_paso3_titulo: 'Jaso oharrak',
    tutorial_paso3_texto: 'Koloreen bidez abisatzen dizugu: berde, laranja edo gorri botika bakoitzaren egoeraren arabera.',
    tutorial_paso4_titulo: 'Partekatu zure familiarekin',
    tutorial_paso4_texto: 'Premium egin zaitez eta kontrolatu familia osoaren botikina toki bakar batetik.',
    tutorial_empezar: 'Hasi',

    // Rol
    rol_titulo: 'Aukeratu zure profila',
    rol_subtitulo: 'Gehien interesatzen zaizkizun funtzioak gomendatuko dizkizugu',
    rol_hogar: 'Etxea',
    rol_hogar_desc: 'Kontrolatu familiaren botikina',
    rol_hospital: 'Ospitalea',
    rol_hospital_desc: 'Stock eta iraungitzeak solairu edo unitateka',
    rol_farmacia: 'Farmazia',
    rol_farmacia_desc: 'Loteak, erreferentziak eta iraungitzeak',
    rol_medico: 'Medikua',
    rol_medico_desc: 'Pazienteko edo espedienteko medikazioa',

    // Registro/Login
    registro_titulo: 'Sortu kontua',
    login_titulo: 'Hasi saioa',
    nombre: 'Izena',
    email: 'Emaila',
    password: 'Pasahitza',
    crear_cuenta: 'Sortu kontua',
    iniciar_sesion: 'Hasi saioa',
    ya_tengo_cuenta: 'Badaukazu kontua? Hasi saioa',
    no_tengo_cuenta: 'Ez daukazu konturik? Izena eman',
    olvide_password: 'Pasahitza ahaztu duzu?',
    recuperar_titulo: 'Berreskuratu pasahitza',
    recuperar_texto: 'Pasahitz berri bat sortzeko esteka bidaliko dizugu',
    recuperar_boton: 'Bidali esteka',
    recuperar_enviado: 'Emaila bidali dizugu. Begiratu sarrera-ontzia.',

    // App principal
    total: 'Guztira',
    pronto: 'Laster',
    caducados: 'Iraungiak',
    tab_medicamentos: '💊 Botikak',
    tab_anadir: '➕ Gehitu',
    tab_alertas: '🔔 Oharrak',
    sin_medicamentos: 'Botikarik gabe. Gehitu lehenengoa!',
    sin_alertas: '✅ Oharrik gabe',
    compartir_mi_botiquin: '👥 Partekatu nire botikina',
    compartir: '👥 Partekatu',
    sin_anuncios: '👑 Iragarkirik gabe — 1,99 €/hilabetea',
    modo_lectura: '👁️ Beste erabiltzaile baten botikina ari zara ikusten irakurketa-moduan. Jabeak bakarrik alda dezake.',
    exportar_pdf: '📄 Esportatu PDF',
    exportar_pdf_premium: '📄 Esportatu PDF (Premium)',
    exportar_generando: '📄 Sortzen...',
    mi_botiquin: 'Nire botikina',
    botiquin_de: 'Botikina:',

    // Estados de medicamentos
    estado_ok: 'Indarrean',
    estado_pronto: 'Laster iraungiko da',
    estado_urgente: 'Iraungitzear',
    estado_caducado: 'Iraungia',
    dias_caducado: 'Duela {dias} egun iraungia',
    dias_caduca_hoy: 'Gaur iraungitzen da',
    dias_caduca_en: '{dias} egunetan iraungiko da',
    sin_fecha: 'Datarik ez',

    // Categorías
    cat_analgesico: 'Analgesikoa',
    cat_antibiotico: 'Antibiotikoa',
    cat_antihistaminico: 'Antihistaminikoa',
    cat_digestivo: 'Lixeriketa',
    cat_vitamina: 'Bitamina',
    cat_otro: 'Bestea',

    // Añadir
    nuevo_medicamento: '💊 Botika berria',
    modo_escribir: '⌨️ Idatzi',
    modo_escanear: '📷 Eskaneatu kodea',
    categoria: 'Kategoria',
    fecha_caducidad: 'Iraungitze-data',
    fecha_caducidad_ayuda: '(kutxan ageri da)',
    cantidad: 'Kopurua (aukerakoa)',
    mes: 'Hilabetea',
    anio: 'Urtea',
    boton_anadir_medicamento: '➕ Gehitu botika',
    escanea_codigo: 'Eskaneatu kode-barra',
    escanea_ayuda: 'Sakatu behean eta egin argazki bat kodeari',
    activar_camara: '📷 Aktibatu kamera',
    buscando_cima: 'CIMAn bilatzen...',
    medicamento_detectado: '✅ Botika detektatu da',
    mira_caducidad_caja: '(begiratu kutxan)',
    guardar_medicamento: '✓ Gorde',

    // Meses
    meses: ['Urtarrila', 'Otsaila', 'Martxoa', 'Apirila', 'Maiatza', 'Ekaina', 'Uztaila', 'Abuztua', 'Iraila', 'Urria', 'Azaroa', 'Abendua'],

    // Perfil
    mi_perfil: 'Nire profila',
    datos_personales: 'Datu pertsonalak',
    recibir_avisos: 'Jaso oharrak emailez botika bat laster iraungitzean',
    guardar_cambios: 'Gorde aldaketak',
    perfil_actualizado: 'Profila ondo eguneratu da',
    cambiar_password: 'Aldatu pasahitza',
    nueva_password: 'Pasahitz berria (gutxienez 6 karaktere)',
    password_cambiada: 'Pasahitza ondo aldatu da',
    zona_peligrosa: 'Eremu arriskutsua',
    eliminar_cuenta_aviso: 'Kontua ezabatzeak zure botika eta datu guztiak betiko ezabatuko ditu. Ezin da desegin.',
    eliminar_mi_cuenta: 'Ezabatu nire kontua',
    escribe_eliminar: 'Idatzi EZABATU berresteko:',
    confirmar_eliminacion: 'Berretsi ezabaketa',
    suscripcion_activa: '👑 Premium harpidetza aktibo',
    suscripcion_descripcion: 'Kudeatu harpidetza, aldatu ordainketa-modua, ikusi fakturak edo ezeztatu nahi duzunean.',
    gestionar_suscripcion: 'Kudeatu harpidetza',
    abriendo: 'Irekitzen...',
    idioma: 'Hizkuntza',

    // Compartir
    compartir_titulo: 'Partekatu botikina',
    compartir_premium_aviso: 'Botikina partekatzea Premium funtzioa da. Egin zaitez Premium familia edo zaintzaileak gonbidatzeko.',
    invitar_familiar: 'Gonbidatu senidea',
    invitar_email: 'Senidearen edo zaintzailearen emaila',
    invitar_boton: 'Bidali gonbidapena',
    invitacion_enviada: 'Gonbidapena bidalia',
    miembros_titulo: 'Botikinaren kideak',
    invitaciones_pendientes: 'Gonbidapenak erantzuteko',
    aceptar: 'Onartu',
    rechazar: 'Ukatu',
    sin_miembros: 'Oraindik ez duzu inor gonbidatu',
    sin_invitaciones: 'Ez duzu gonbidapenik erantzuteko',
    limite_invitados: '4 gonbidaturen mugara iritsi zara',

    // Errores comunes
    error_email_password: 'Email edo pasahitza okerra',
    error_email_existe: 'Email hau erregistratuta dago',
    error_generico: 'Errore bat gertatu da. Saiatu berriro.',
    error_password_corta: 'Pasahitzak gutxienez 6 karaktere izan behar ditu',
    error_completa_campos: 'Bete eremu guztiak',
    medicamento_anadido: '{nombre} gehitua',
    medicamento_eliminado: 'Botika ezabatua',
    rellena_nombre_fecha: 'Idatzi izena eta aukeratu data',
    solo_dueno_anadir: 'Jabeak bakarrik gehitu dezake',
    solo_dueno_eliminar: 'Jabeak bakarrik ezabatu dezake',
    pdf_descargado: 'PDFa deskargatua',
    pdf_premium_aviso: 'PDF esportatzea Premium funtzioa da',
  },

  ca: {
    // Generales
    cargando: 'Carregant...',
    guardar: 'Desa',
    cancelar: 'Cancel·la',
    volver: '← Torna',
    confirmar: 'Confirma',
    eliminar: 'Elimina',
    salir: 'Surt',
    siguiente: 'Següent',
    anterior: 'Anterior',

    // Tutorial
    tutorial_paso1_titulo: 'Benvingut a MediCaduca',
    tutorial_paso1_texto: "L'aplicació per controlar la caducitat dels teus medicaments. Fàcil, ràpida i gratuïta.",
    tutorial_paso2_titulo: 'Afegeix els teus medicaments',
    tutorial_paso2_texto: "Escaneja el codi de barres o escriu a mà el nom i la data de caducitat.",
    tutorial_paso3_titulo: 'Rep alertes',
    tutorial_paso3_texto: "T'avisem amb colors: verd, taronja o vermell segons l'estat de cada medicament.",
    tutorial_paso4_titulo: 'Comparteix amb la teva família',
    tutorial_paso4_texto: 'Fes-te Premium i controla la farmaciola de tota la família des d\'un sol lloc.',
    tutorial_empezar: 'Comença',

    // Rol
    rol_titulo: 'Tria el teu perfil',
    rol_subtitulo: "Et recomanarem les funcions que més t'interessen",
    rol_hogar: 'Llar',
    rol_hogar_desc: 'Controla la farmaciola de la teva família',
    rol_hospital: 'Hospital',
    rol_hospital_desc: 'Estoc i caducitats per planta o unitat',
    rol_farmacia: 'Farmàcia',
    rol_farmacia_desc: 'Lots, referències i caducitats',
    rol_medico: 'Metge',
    rol_medico_desc: 'Medicació per pacient o expedient',

    // Registro/Login
    registro_titulo: 'Crear compte',
    login_titulo: 'Inicia la sessió',
    nombre: 'Nom',
    email: 'Correu electrònic',
    password: 'Contrasenya',
    crear_cuenta: 'Crear compte',
    iniciar_sesion: 'Inicia la sessió',
    ya_tengo_cuenta: 'Ja tens compte? Inicia la sessió',
    no_tengo_cuenta: 'No tens compte? Registra\'t',
    olvide_password: 'Has oblidat la contrasenya?',
    recuperar_titulo: 'Recupera la contrasenya',
    recuperar_texto: "T'enviarem un enllaç per crear una contrasenya nova",
    recuperar_boton: 'Envia enllaç',
    recuperar_enviado: "T'hem enviat un correu. Revisa la safata d'entrada.",

    // App principal
    total: 'Total',
    pronto: 'Aviat',
    caducados: 'Caducats',
    tab_medicamentos: '💊 Medicaments',
    tab_anadir: '➕ Afegir',
    tab_alertas: '🔔 Alertes',
    sin_medicamentos: 'Sense medicaments. Afegeix el primer!',
    sin_alertas: '✅ Sense alertes pendents',
    compartir_mi_botiquin: '👥 Compartir la meva farmaciola',
    compartir: '👥 Compartir',
    sin_anuncios: '👑 Sense anuncis — 1,99 €/mes',
    modo_lectura: "👁️ Estàs veient la farmaciola d'un altre usuari en mode de lectura. Només el propietari la pot modificar.",
    exportar_pdf: '📄 Exportar PDF',
    exportar_pdf_premium: '📄 Exportar PDF (Premium)',
    exportar_generando: '📄 Generant...',
    mi_botiquin: 'La meva farmaciola',
    botiquin_de: 'Farmaciola de',

    // Estados de medicamentos
    estado_ok: 'En vigor',
    estado_pronto: 'Caduca aviat',
    estado_urgente: 'Molt aviat',
    estado_caducado: 'Caducat',
    dias_caducado: 'Caducat fa {dias} dies',
    dias_caduca_hoy: 'Caduca avui',
    dias_caduca_en: 'Caduca en {dias} dies',
    sin_fecha: 'Sense data',

    // Categorías
    cat_analgesico: 'Analgèsic',
    cat_antibiotico: 'Antibiòtic',
    cat_antihistaminico: 'Antihistamínic',
    cat_digestivo: 'Digestiu',
    cat_vitamina: 'Vitamina',
    cat_otro: 'Altre',

    // Añadir
    nuevo_medicamento: '💊 Nou medicament',
    modo_escribir: '⌨️ Escriure',
    modo_escanear: '📷 Escanejar codi',
    categoria: 'Categoria',
    fecha_caducidad: 'Data de caducitat',
    fecha_caducidad_ayuda: '(és a la caixa)',
    cantidad: 'Quantitat (opcional)',
    mes: 'Mes',
    anio: 'Any',
    boton_anadir_medicamento: '➕ Afegir medicament',
    escanea_codigo: 'Escaneja el codi de barres',
    escanea_ayuda: 'Prem a sota i fes una foto del codi',
    activar_camara: '📷 Activar càmera',
    buscando_cima: 'Buscant a CIMA...',
    medicamento_detectado: '✅ Medicament detectat',
    mira_caducidad_caja: '(mira-la a la caixa)',
    guardar_medicamento: '✓ Desa',

    // Meses
    meses: ['Gener', 'Febrer', 'Març', 'Abril', 'Maig', 'Juny', 'Juliol', 'Agost', 'Setembre', 'Octubre', 'Novembre', 'Desembre'],

    // Perfil
    mi_perfil: 'El meu perfil',
    datos_personales: 'Dades personals',
    recibir_avisos: 'Rebre avisos per correu quan un medicament caduqui aviat',
    guardar_cambios: 'Desa els canvis',
    perfil_actualizado: 'Perfil actualitzat correctament',
    cambiar_password: 'Canvia la contrasenya',
    nueva_password: 'Nova contrasenya (mín. 6 caràcters)',
    password_cambiada: 'Contrasenya canviada correctament',
    zona_peligrosa: 'Zona perillosa',
    eliminar_cuenta_aviso: 'Eliminar el teu compte esborrarà tots els teus medicaments i dades per sempre. No es pot desfer.',
    eliminar_mi_cuenta: 'Eliminar el meu compte',
    escribe_eliminar: 'Escriu ELIMINAR per confirmar:',
    confirmar_eliminacion: 'Confirmar eliminació',
    suscripcion_activa: '👑 Subscripció Premium activa',
    suscripcion_descripcion: 'Gestiona la teva subscripció, canvia el mètode de pagament, mira les teves factures o cancel·la quan vulguis.',
    gestionar_suscripcion: 'Gestionar subscripció',
    abriendo: 'Obrint...',
    idioma: 'Idioma',

    // Compartir
    compartir_titulo: 'Compartir farmaciola',
    compartir_premium_aviso: 'Compartir la farmaciola és una funció Premium. Fes-te Premium per convidar familiars o cuidadors.',
    invitar_familiar: 'Convidar familiar',
    invitar_email: 'Correu del familiar o cuidador',
    invitar_boton: 'Enviar invitació',
    invitacion_enviada: 'Invitació enviada',
    miembros_titulo: 'Membres de la farmaciola',
    invitaciones_pendientes: 'Invitacions pendents',
    aceptar: 'Acceptar',
    rechazar: 'Rebutjar',
    sin_miembros: 'Encara no has convidat ningú',
    sin_invitaciones: 'No tens invitacions pendents',
    limite_invitados: 'Has arribat al màxim de 4 convidats',

    // Errores comunes
    error_email_password: 'Correu o contrasenya incorrectes',
    error_email_existe: 'Aquest correu ja està registrat',
    error_generico: 'S\'ha produït un error. Torna-ho a provar.',
    error_password_corta: 'La contrasenya ha de tenir almenys 6 caràcters',
    error_completa_campos: 'Omple tots els camps',
    medicamento_anadido: '{nombre} afegit',
    medicamento_eliminado: 'Medicament eliminat',
    rellena_nombre_fecha: 'Escriu el nom i selecciona la data',
    solo_dueno_anadir: 'Només el propietari pot afegir',
    solo_dueno_eliminar: 'Només el propietari pot eliminar',
    pdf_descargado: 'PDF descarregat',
    pdf_premium_aviso: 'Exportar PDF és una funció Premium',
  }
}

// Hook para usar las traducciones
export function t(idioma, clave, sustituciones = {}) {
  const textos = TRADUCCIONES[idioma] || TRADUCCIONES.es
  let texto = textos[clave] || TRADUCCIONES.es[clave] || clave

  if (Array.isArray(texto)) return texto

  // Sustituciones tipo {nombre} → valor
  Object.keys(sustituciones).forEach(k => {
    texto = texto.replace(`{${k}}`, sustituciones[k])
  })

  return texto
}

export const IDIOMAS = [
  { codigo: 'es', nombre: 'Español' },
  { codigo: 'eu', nombre: 'Euskara' },
  { codigo: 'ca', nombre: 'Català' },
]